plugins {
    id 'com.gradleup.shadow'
}

architectury {
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}
repositories {
    maven {
        url = "https://maven.terraformersmc.com/releases/"
    }
    // Dépôt de Cloth Config au cas où il manquerait aussi à ce module
    maven {
        url = "https://maven.shedaniel.me/"
    }
}
dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Fabric API.
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    // Architectury API.
    modImplementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"

    //Cloth Config
    modApi ("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"){
        exclude group: "net.fabricmc.fabric-api"
    }
    include "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}"

    // ModMenu API
    modApi "com.terraformersmc:modmenu:${rootProject.modmenu_version}"

    // TEAMREBORN ENERGY API
    include modApi("teamreborn:energy:${rootProject.teamreborn_energy_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    //REI
    modCompileOnlyApi  "me.shedaniel:RoughlyEnoughItems-api-fabric:${rootProject.rei_version}"
    modCompileOnlyApi  "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${rootProject.rei_version}"

    //JEI
    modCompileOnlyApi("mezz.jei:jei-${rootProject.minecraft_version}-fabric-api:${rootProject.jei_version}")

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: inputs.properties.version
    }
    // Copy AccessWidener file to fabric module
    from(project(":common").file("src/main/resources/vibranium.accesswidener"))
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

loom {
    accessWidenerPath = project(":common").file("src/main/resources/vibranium.accesswidener")

    runs {
        datagen {
            client()
            name("Minecraft Data")
            runDir("build/datagen")

            // Syntaxe moderne pour injecter les arguments VM dans Loom 1.17+
            vmArgs(
                    "-Dfabric-api.datagen",
                    "-Dfabric-api.datagen.output-dir=${project(":common").file("src/main/generated")}",
                    "-Dfabric-api.datagen.modid=vibranium"
            )
        }
    }
}