# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
shadow_version= 9.4.3

# Mod properties
mod_version = 1.0.0-beta1
maven_group = io.github.leiriad
archives_name = vibranium
enabled_platforms = fabric,neoforge
mod_name=Vibranium
mod_description=Brings the power of vibranium to Minecraft
mod_author=Leiriad
mod_license=Apache-2.0
mod_repository=https://github.com/Leiriad/Vibranium

# Minecraft properties
minecraft_version = 26.2
supported_minecraft_version=26.2

# Dependencies
architectury_api_version = 21.0.7
architectury_plugin_version = 3.5-SNAPSHOT
architectury_loom_version = 1.17-SNAPSHOT
fabric_loader_version = 0.19.5
fabric_api_version = 0.160.0+26.2
neoforge_version = 26.2.0.52-beta
cloth_config_version=26.2.155
teamreborn_energy_version=4.1.0
modmenu_version=20.0.2
rei_version=26.2.820
jei_version=30.32.0.217

fabric.loom.disableDependencyVerification=true
architectury.loom.disableDependencyVerification=true